$(document).ready(function(){
    $(".button1").hover(function(){
      $("#p1").fadeOut(3000);
    });
    $(".button2").hover(function(){
      $("#p2").fadeOut(3000);
    });
    $(".button3").hover(function(){
      $("#p3").fadeOut(3000);
    });
    $(".button4").hover(function(){
      $("#p4").fadeOut(3000);
    });
    $(".button5").hover(function(){
      $("#p5").fadeOut(3000);
    });
    $(".button6").hover(function(){
      $("#p6").fadeOut(3000);
    });
    $(".button7").hover(function(){
      $("#p7").fadeOut(3000);
    });
    $(".button8").hover(function(){
      $("#p8").fadeOut(3000);
    });
    $(".button9").hover(function(){
      $("#p9").fadeOut(3000);
    });
  });